name: Run JMeter Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

        - name: Set up JMeter and Install Dummy Sampler Plugin
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk unzip wget

        # Download and extract JMeter
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xzf apache-jmeter-5.5.tgz
        cd apache-jmeter-5.5

        # Download Plugins Manager JAR
        wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.11/jmeter-plugins-manager-1.11.jar -O lib/ext/jmeter-plugins-manager.jar

        # Download cmdrunner (required by PluginsManagerCMD.sh)
        wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar -O lib/cmdrunner-2.3.jar

        # Install Plugin Manager CMD tool
        java -cp lib/ext/jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

        # Export path so JMeter commands are available
        export PATH=$PATH:$PWD/bin

        # Install Dummy Sampler plugin
        bin/PluginsManagerCMD.sh install dummy

        # Store path for next steps
        echo "JMETER_PATH=$PWD" >> $GITHUB_ENV


    - name: Run JMeter Test Plan
      run: |
        export PATH=$PATH:$JMETER_PATH/bin
        jmeter -n -t BatchTestBooks.jmx -l results.csv

    - name: Upload Result File
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: results.csv
